### ISSUE TITLE
api spot service do not start

### ISSUE THREAD

**Issue by paragparandkar** [chefArchitect/apispots-testing-bdd#3]
Followed the instruction on getting started page, 
parag@parag1:~$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
apispots/bdd-api-testing   latest              90f79be615a1        12 weeks ago        550.2 MB

docker run -d -p 3000:3000 --name="apispots-bdd" apispots/bdd-api-testing

**docker logs show following error -**

docker logs -f apispots-bdd

/app/node_modules/hapi/lib/index.js:5
const Server = require('./server');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/app/rest/services/BootstrapService.js:11:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by xrysanthos** [comment]
@paragparandkar thanks for the ticket.  Fixed the issue today and updated the Docker image.  Should be available in a while.
